# All the below fields are required for successful operator registration.

# To learn more about operator fields
# https://github.com/Layr-Labs/eigenlayer-contracts/blob/92ccacc868785350973afc15e90a18dcd39fbc0b/src/contracts/interfaces/IDelegationManager.sol#L21:
operator:
  # This is the standard Ethereum address format (ex: 0x6a8c0D554a694899041E52a91B4EC3Ff23d8aBD5) of your operator
  # which is the ecdsa key you created or imported using EigenLayer CLI
  address:
  # This is the standard Ethereum address format (0x...)
  # This is the address which operator will use to approve delegation requests from stakers.
  # if set, this address must sign and approve new delegation from Stakers to this Operator
  # For now, you can leave it  with the default value for un-gated delegation requests
  # Once we enable gated delegation requests, you can update this field with the address of the approver
  delegation_approver_address: 0x0000000000000000000000000000000000000000
  # Please refer to this link for more details on this field https://github.com/Layr-Labs/eigenlayer-contracts/blob/92ccacc868785350973afc15e90a18dcd39fbc0b/src/contracts/interfaces/IDelegationManager.sol#L33:
  # Please keep this field to 0, and it can be updated later using EigenLayer CLI
  staker_opt_out_window_blocks: 0
  metadata_url: https://raw.githubusercontent.com/Layr-Labs/eigenlayer-cli/master/pkg/operator/config/metadata-example.json

# EigenLayer Delegation manager contract address
# For the testnet address, refer to here: https://github.com/layr-labs/eigenlayer-contracts/?tab=readme-ov-file#current-testnet-deployment
# For the mainnet address, refer to here: https://github.com/layr-labs/eigenlayer-contracts/?tab=readme-ov-file#current-mainnet-deployment
el_delegation_manager_address:

# ETH RPC URL to the ethereum node you are using for on-chain operations
eth_rpc_url: http://localhost:8545

# Signer Type to use
# Supported values: local_keystore, fireblocks, web3
signer_type: local_keystore

# Full path to local ecdsa private key store file
private_key_store_path: <path-to>/test.ecdsa.key.json

# Chain ID: 1 for mainnet, 17000 for holesky, 31337 for local
chain_id: 17000

# If you are using Fireblocks as your signer, please provide the following details
fireblocks:
    # Fireblocks API Key
    api_key:

    # Fireblocks Secret Key storage type: plain_text, aws_secret_manager
    secret_storage_type:

    # Fireblocks Secret Key
    # If secret_storage_type is plain_text, this should be the secret key
    # If secret_storage_type is aws_secret_manager, this should be the secret key name in AWS Secret Manager
    secret_key:

    # Fireblocks Base URL
    base_url: https://api.fireblocks.io/

    # Fireblocks Vault Account Name
    vault_account_name:

    # Fireblocks AWS Region (if secret_storage_type is aws_secret_manager)
    aws_region:

    # Fireblocks API Timeout
    timeout: 3

# If you are using web3 as your signer, please provide the following details
# https://docs.web3signer.consensys.io/
web3:
  # Web3 Signer URL
  url: